name: conn_gui
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - cython
  - docopt
  - easydict
  - einops
  - h5py
  - matplotlib
  - networkx
  - numpy
  - opencv
  - pandas
  - pillow
  - pyclipper
  - pyside6
  - python-bidi
  - python-json-logger
  - pyyaml
  - scikit-image
  - scipy
  - shapely
  - tensorboardx
  - tqdm
  - yacs
  - pip:
      - easyocr
      - schemdraw
      - torch
      - torchaudio
      - torchvision
      - ultralytics
